### PR TITLE
Add english translation

### PR DESCRIPTION
**Pull request by Solynhoo**
Hi!
I recently found this [Post](https://x.com/azakasekai_/status/1759326049262019025?s=46) on **X** which talks about this repo, I think it would be nice to add some translation for non-chinese speakers, I translated it with **ChatGPT** so it may be wrong in some words

### CODE REVIEW

**Review by Solynhoo — COMMENTED** [review]
* If any Chinese government people are seeing this, I have nothing to do with this leak, I’m just a dumb boy who saw this on X!

**Comment by broman** [comment]
save the nothing burger PRs for Hacktoberfest and save the translating for real translators

**Comment by Solynhoo** [comment]
Probably all the translations were wrong, gonna let a real Mandarin speaker do the translations (if they want).

**Comment by Solynhoo** [comment]
> save the nothing burger PRs for Hacktoberfest and save the translating for real translators

Yep, gonna let the translation for real translators, thanks for the feedback tho

**Pull request closed without merging**
